import type { TriageInput } from "@/types";
import type { AiTriageResponse } from "./response.parser";

/**
 * Rule-based triage classifier — used when Gemini is unavailable.
 * Conservative: always errs toward higher acuity (lower ESI number).
 */
export function fallbackClassify(input: TriageInput): AiTriageResponse {
  const flags: string[] = [];
  let esiLevel: AiTriageResponse["esiLevel"] = "ESI_3";
  let urgencyScore = 0.5;

  const combined = [...input.symptoms, input.chiefComplaint]
    .join(" ")
    .toLowerCase();

  // ESI_1 — immediate life threats
  if (
    combined.includes("not breathing") ||
    combined.includes("cardiac arrest") ||
    combined.includes("unresponsive") ||
    combined.includes("unconscious") ||
    combined.includes("no pulse")
  ) {
    esiLevel = "ESI_1";
    urgencyScore = 1.0;
    flags.push("ALTERED_CONSCIOUSNESS");
  }
  // ESI_2 — high risk
  else if (
    combined.includes("chest pain") ||
    combined.includes("difficulty breathing") ||
    combined.includes("can't breathe") ||
    combined.includes("stroke") ||
    combined.includes("facial droop") ||
    combined.includes("anaphylaxis") ||
    combined.includes("severe bleeding") ||
    combined.includes("coughing blood") ||
    input.painScale >= 8
  ) {
    esiLevel = "ESI_2";
    urgencyScore = 0.8;
    if (combined.includes("chest pain") || combined.includes("chest tightness")) flags.push("CHEST_PAIN");
    if (combined.includes("difficulty breathing") || combined.includes("can't breathe")) flags.push("DIFFICULTY_BREATHING");
    if (combined.includes("stroke") || combined.includes("facial droop")) flags.push("STROKE_SYMPTOMS");
    if (combined.includes("bleeding")) flags.push("SEVERE_BLEEDING");
    if (combined.includes("anaphylaxis") || combined.includes("allergic reaction")) flags.push("ANAPHYLAXIS");
  }

  // Infant fever override → ESI_2
  if (input.age < 1 && combined.includes("fever")) {
    esiLevel = "ESI_2";
    urgencyScore = 0.85;
    flags.push("PEDIATRIC_FEVER");
  }

  return {
    esiLevel,
    urgencyScore,
    urgencyFlags: flags as AiTriageResponse["urgencyFlags"],
    clinicalSummary:
      "Assessment generated by rule-based fallback (AI service unavailable). " +
      "Clinical review by a triage nurse is mandatory before acting on this assessment.",
    differentials: [
      {
        condition: "Undetermined — manual assessment required",
        probability: "high",
        reasoning: "AI service unavailable; symptom pattern matched rule-based classifier only.",
      },
    ],
    recommendations: [
      { action: "Immediate manual nurse assessment", priority: "urgent" },
      { action: "Do not rely solely on this assessment — AI fallback was used", priority: "immediate" },
    ],
    redFlags: ["AI fallback active — human triage nurse review is mandatory"],
  };
}
